apiVersion: v1
kind: Service
metadata:
  name: flask-monitor
  namespace: ashapp
spec:
  selector:
    app: flask-monitor
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
  type: ClusterIP

