apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""  # must match StatefulSet PVC
  hostPath:
    path: /mnt/data/mysql  # Make sure this path exists on your node
