# ================================
# PersistentVolume for MySQL
# ================================
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete   # auto-cleanup when PVC is deleted
  hostPath:                                # local path on node
    path: /mnt/data/mysql
  storageClassName: mysql-storage-class
---
# ================================
# StorageClass (optional, if not exists)
# ================================
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-storage-class
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
