apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: ashapp
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete   # Auto-cleanup when PVC is deleted
  hostPath:                                # For testing (on your node)
    path: /mnt/data/mysql
  storageClassName: mysql-storage-class
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: ashapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: mysql-storage-class
